sudo: required
services:
  - docker

before_install:
  - docker build -t robybala/docker-react -f Dockerfile.dev .

script:
  - docker run robybala/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "name-of-your-s3-bucket"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_ACCESS_KEY"